// Array of quotes
var quotes = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "Your time is limited, don’t waste it living someone else’s life. – Steve Jobs",
    "Stay hungry, stay foolish. – Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "Friendship is the hardest thing in the world to explain. It’s not something you learn in school. But if you have not learned the meaning of friendship, you really have not learned anything. –  Muhammad Ali",
    "Do not make friends who are comfortable to be with. Make friends who will force you to lever yourself up. – Thomas J. Watson",
    "The most beautiful discovery true friends make is that they can grow separately without growing apart. – Elisabeth Foley",
    "Each friend represents a world in us, a world possibly not born until they arrive, and it is only by this meeting that a new world is born. – Anais Nin",
    "Life is partly what we make it, and partly what it is made by the friends we choose. – Tennessee Williams",
    "They may forget what you said, but they will never forget how you made them feel. –Carl W. Buechner",
    "Find a group of people who challenge and inspire you; spend a lot of time with them, and it will change your life. – Amy Poehler",
    "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone. – Audrey Hepburn",
    "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart. – Helen Keller",
    "Happiness can be found even in the darkest of times, if one only remembers to turn on the light. – Dumbledore",
    "A real friend is one who walks in when the rest of the world walks out.– Walter Winchell",
    "If you live to be 100, I hope I live to be 100 minus 1 day, so I never have to live without you.– Winnie the Pooh",
    "I like to listen. I have learned a great deal from listening carefully. Most people never listen.– Ernest Hemingway",
    "Friendship is born at that moment when one person says to another, ‘What! You too? I thought I was the only one.– C.S. Lewis",
    "True friendship comes when the silence between two people is comfortable.– David Tyson",
    "Sweet is the memory of distant friends! Like the mellow rays of the departing sun, it falls tenderly, yet sadly, on the heart.– Washington Irving",
    "There’s not a word yet for old friends who’ve just met.– Jim Henson",
    "A single rose can be my garden… a single friend, my world.– Leo Buscaglia",
    "Don’t make friends who are comfortable to be with. Make friends who will force you to lever yourself up.– Thomas J. Watson",
    "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.— Dale Carnegie",
    "A friend is someone who understands your past, believes in your future, and accepts you just the way you are.– Unknown",
    "What you do not want done to yourself, do not do to others.– Confucius",
    "Ultimately the bond of all companionship, whether in marriage or in friendship, is conversation.– Oscar Wilde",
    "How many slams in an old screen door? Depends how loud you shut it. How many slices in a bread? Depends how thin you cut it. How much good inside a day? Depends how good you live them. How much love inside a friend? Depends how much you give them.–Shel Silverstein",
    "A true friend never gets in your way unless you happen to be going down.– Arnold H. Glasgow",
    "I don’t need a friend who changes when I change and who nods when I nod; my shadow does that much better.– Plutarch",
    "In everyone’s life, at some time, our inner fire goes out. It is then burst into flame by an encounter with another human being. We should all be thankful for those people who rekindle the inner spirit.– Albert Schweitzer",
    "The real test of friendship is can you literally do nothing with the other person? Can you enjoy those moments of life that are utterly simple?– Eugene Kennedy",
    "A loyal friend laughs at your jokes when they are not so good, and sympathizes with your problems when they are not so bad.– Arnold H. Glasgow",
    "It is not a lack of love, but a lack of friendship that makes unhappy marriages.– Friedrich Nietzsche",
    "Friendship is the hardest thing in the world to explain. It’s not something you learn in school. But if you haven’t learned the meaning of friendship, you really have not learned anything.– Muhammad Ali",
    "If ever there is tomorrow when we are not together… there is something you must always remember. You are braver than you believe, stronger than you seem, and smarter than you think. But the most important thing is, even if we’re apart… I’ll always be with you.– Winnie the Pooh",
    "Growing apart doesn’t change the fact that for a long time we grew side by side; our roots will always be tangled. I’m glad for that.– Ally Condie",
    "One’s friends are that part of the human race with which one can be human.– George Santayana",
    "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.– Audrey Hepburn",
    "Be slow to fall into friendship; but when thou art in, continue firm and constant.– Socrates",
    "One measure of friendship consists not in the number of things friends can discuss, but in the number of things they need no longer mention.– Clifton Fadiman",
    "Never idealize others. They will never live up to your expectations. Don’t over-analyze your relationships. Stop playing games. A growing relationship can only be nurtured by genuineness. – Leo F. Buscaglia",
    "In the End, we will remember not the words of our enemies, but the silence of our friends.– Martin Luther King, Jr.",
    "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.”– Marcel Proust",
    "Tis the privilege of friendship to talk nonsense, and to have her nonsense respected.– Charles Lamb",
    "If you go looking for a friend, you’re going to find they’re very scarce. If you go out to be a friend, you’ll find them everywhere.– Zig Ziglar",
    "You can always tell a real friend: when you’ve made a fool of yourself he doesn’t feel you’ve done a permanent job.– Laurence J. Peter",
    "Keep away from those who try to belittle your ambitions. Small people always do that, but the really great make you believe that you too can become great.– Mark Twain",
    "Flatter me, and I may not believe you. Criticize me, and I may not like you. Ignore me, and I may not forgive you. Encourage me, and I will not forget you. Love me and I may be forced to love you.– William Arthur Ward",
    "No person is your friend who demands your silence, or denies your right to grow.– Alice Walker",
    "Friendship is the only cement that will ever hold the world together.– Woodrow T. Wilson",
    "Friends are those rare people who ask how we are and then wait to hear the answer.– Ed Cunningham",
    "Anybody can sympathize with the sufferings of a friend, but it requires a very fine nature to sympathize with a friend’s success.– Oscar Wilde",
    "Some of the biggest challenges in relationships come from the fact that most people enter a relationship in order to get something: they’re trying to find someone who’s going to make them feel good. In reality, the only way a relationship will last is if you see your relationship as a place that you go to give, and not a place that you go to take.— Anthony Robbins",
    "The most beautiful discovery true friends make is that they can grow separately without growing apart.– Elisabeth Foley",
    "There’s one sad truth in life I’ve found While journeying east and west –The only folks we really wound Are those we love the best. We flatter those we scarcely know, we please the fleeting guest, and deal full many a thoughtless blow to those who love us best.– Ella Wheeler Wilcox",
    "Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.— Oprah Winfrey",
    "Do not keep on with a mockery of friendship after the substance is gone — but part, while you can part friends. Bury the carcass of friendship: it is not worth embalming.– William Hazlitt",
    "A good friend can tell you what is the matter with you in a minute. He may not seem such a good friend after telling.– Arthur Brisbane",
    "Many a person has held close, throughout their entire lives, two friends that always remained strange to one another, because one of them attracted by virtue of similarity, the other by difference.– Emil Ludwig",
    "A good word is an easy obligation; but not to speak ill requires only our silence; which costs us nothing.— John Tillotson",
    "When you stop expecting people to be perfect, you can like them for who they are.– Donald Miller",
    "Each friend represents a world in us, a world possibly not born until they arrive, and it is only by this meeting that a new world is born.– Anais Nin",
    "If you make friends with yourself you will never be alone.– Maxwell Maltz",
    "A true friend is someone who thinks that you are a good egg even though he knows that you are slightly cracked.– Bernard Meltzer",
    "The greatest compliment that was ever paid me was when someone asked me what I thought, and attended to my answer.— Henry David Thoreau",
    "People are lonely because they build walls instead of bridges.— Joseph F. Newton Men",
    "Friendship is like a glass ornament, once it is broken it can rarely be put back together exactly the same way.– Charles Kingsley",
    "A friend knows the song in my heart and sings it to me when my memory fails.– Donna Roberts",
    "There is nothing better than a friend, unless it is a friend with chocolate. – Linda Grayson",
    "Sometimes being a friend means mastering the art of timing. There is a time for silence. A time to let go and allow people to hurl themselves into their own destiny. And a time to prepare to pick up the pieces when it’s all over.– Gloria Naylor",
    "It is the friends you can call up at 4 a.m. that matter.– Marlene Dietrich",
    "There is magic in long-distance friendships. They let you relate to other human beings in a way that goes beyond being physically together and is often more profound. – Diana Cortes",
    "Someone to tell it to is one of the fundamental needs of human beings.— Miles Franklin",
    "It is not so much our friends’ help that helps us, as the confidence of their help.– Epicurus",
    "Whenever you’re in conflict with someone, there is one factor that can make the difference between damaging your relationship and deepening it. That factor is attitude.– William James",
    "Life is partly what we make it, and partly what it is made by the friends we choose.”– Tennessee Williams",
    "The tender friendships one gives up, on parting, leave their bite on the heart, but also a curious feeling of a treasure somewhere buried.– Antoine de Saint-Exupéry",
    "Do I not destroy my enemies when I make them my friends?– Abraham Lincoln",
    "A friend is a person with whom I may be sincere. Before him I may think aloud. I am arrived at last in the presence of a man so real and equal, that I may drop even those undermost garments of dissimulation, courtesy, and second thought, which men never put off, and may deal with him with the simplicity and wholeness with which one chemical atom meets another. – Ralph Waldo Emerson",
    "The best time to make friends is before you need them.– Ethel Barrymore",
    "If it’s very painful for you to criticize your friends — you’re safe in doing it. But if you take the slightest pleasure in it, that’s the time to hold your tongue.– Alice Duer Miller",
    "In the sweetness of friendship let there be laughter, for in the dew of little things the heart finds its morning and is refreshed.– Khalil Gibran",
    "Things are never quite as scary when you’ve got a best friend.– Bill Watterson",
    "Truly great friends are hard to find, difficult to leave, and impossible to forget.– Unknown",
    "They may forget what you said, but they will never forget how you made them feel.– Carl W. Buechner",
    "Nothing makes the earth seem so spacious as to have friends at a distance; they make the latitudes and longitudes.– Henry David Thoreau",
    "A true friend is someone who is there for you when he’d rather be anywhere else.– Len Wein",
    "It is one of the blessings of old friends that you can afford to be stupid with them.– Ralph Waldo Emerson",
    "A friend is one who knows you and loves you just the same.– Elbert Hubbard",
    "Friendship marks a life even more deeply than love. Love risks degenerating into obsession, friendship is never anything but sharing.– Elie Wiesel",
    "We cannot tell the precise moment when friendship is formed. As in filling a vessel drop by drop, there is at last a drop which makes it run over; so in a series of kindnesses there is at last one which makes the heart run over.– Ray Bradbury",
    "Try to be a rainbow in someone’s cloud.– Maya Angelou",
    "I cannot even imagine where I would be today were it not for that handful of friends who have given me a heart full of joy. Let’s face it, friends make life a lot more fun.– Charles R. Swindoll",
    "Many people will walk in and out of your life, but only true friends will leave footprints in your heart.– Eleanor Roosevelt",
    "One of the most beautiful qualities of true friendship is to understand and to be understood.– Seneca",
    "A man’s friendships are one of the best measures of his worth.– Charles Darwin",
    "Friends show their love in times of trouble, not in happiness.– Euripides",
    "Friends are people who know you really well and like you anyway.– Greg Tamblyn",
    "Friendship improves happiness, and abates misery, by doubling our joys, and dividing our grief.– Marcus Tullius Cicero",
    "True friendship ought never to conceal what it thinks.– St. Jerome",
    "I would rather walk with a friend in the dark, than alone in the light.– Helen Keller",
    "A good friend is a connection to life — a tie to the past, a road to the future, the key to sanity in a totally insane world.– Lois Wyse",
    "One of the tasks of true friendship is to listen compassionately and creatively to the hidden silences. Often secrets are not revealed in words, they lie concealed in the silence between the words or in the depth of what is unsayable between two people.– John O’Donohue",
    "A friend is someone who makes it easy to believe in yourself.– Heidi Wills",
    "Awards become corroded. Friends gather no dust.– Jesse Owens",
    "A friend is someone who gives you total freedom to be yourself — and especially to feel, or not feel. Whatever you happen to be feeling at any moment is fine with them. That’s what real love amounts to – letting a person be what he really is.– Jim Morrison",
    "Friendship is like money, easier made than kept.– Samuel Butler",
    "Friendship multiplies the good of life and divides the evil.”– Baltasar Gracian",
    "Friends are the family you choose.– Jess C. Scott",
    "My best friend is the one who brings out the best in me.– Henry Ford",
    "The most I can do for my friend is simply be his friend. – Henry David Thoreau",
    "Friends are relatives you make for yourself.– Eustache Deschamps",
    "Blessed are they who have the gift of making friends, for it is one of God’s greatest gifts. It involves many things, but above all the power of going out of one’s self and appreciating what is noble and loving in another.”– Thomas Hughes",
    "Friendship is always a sweet responsibility, never an opportunity.– Khalil Gibran",
    "A friend to all is a friend to none.– Aristotle",
    "A snowball in the face is surely the perfect beginning to a lasting friendship.– Markus Zusak",
    "Do not save your loving speeches for your friends till they are dead; do not write them on their tombstones, speak them rather now instead.– Anna Cummins",
    "We’re born alone, we live alone, we die alone. Only through our love and friendship can we create the illusion for the moment that we’re not alone.– Orson Welles",
    "When we honestly ask ourselves which person in our lives means the most to us, we often find that it is those who, instead of giving advice, solutions, or cures, have chosen rather to share our pain and touch our wounds with a warm and tender hand.– Henri Nouwen",
    "All love that has not friendship for its base, is like a mansion built upon the sand.– Ella Wheeler Wilcox",
    "Friends are the siblings God never gave us.– Mencius",
    "If we treated ourselves as well as we treated our best friend, can you imagine?– Meghan Markle",
    "Find a group of people who challenge and inspire you; spend a lot of time with them, and it will change your life.– Amy Poehler",
    "Only your real friends will tell you when your face is dirty.– Sicilian Proverb",
    "Don’t be dismayed at goodbyes. A farewell is necessary before you can meet again. And meeting again, after moments or lifetimes, is certain for those who are friends.– Richard Bach",
    "There is nothing like puking with somebody to make you into old friends.– Sylvia Plath",
    "Men kick friendship around like a football, but it doesn’t seem to crack. Women treat it like glass and it goes to pieces.– Anne Morrow Lindbergh",
    "Fate chooses your relations, you choose your friends.– Jacques Delille",
    "Friends should be like books, few, but hand-selected.– C.J. Langenhoven",
    "Friendship is a wildly underrated medication.– Anna Deavere Smith",
    "Some people arrive and make such a beautiful impact on your life, you can barely remember what life was like without them.– Anna Taylor",
    "A good friend is like a four-leaf clover; hard to find and lucky to have.– Irish Proverb",
    "Where there are friends, there is wealth.– Titus Maccius Plautus",
    "True friendship is like sound health; the value of it is seldom known until it is lost.”– Charles Caleb Colton",
    "A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.– William Shakespeare",
    "Be slow in choosing a friend, slower in changing.– Benjamin Franklin",
    "True friendship can afford true knowledge. It does not depend on darkness and ignorance.– Henry David Thoreau",
    "Make new friends, but keep the old; Those are silver, these are gold.– Joseph Parry", 
    "The holy passion of Friendship is of so sweet and steady and loyal and enduring a nature that it will last through a whole lifetime, if not asked to lend money.– Mark Twain",
    "A true friend stabs you in the front.– Oscar Wilde",
    "There is nothing on this earth more to be prized than true friendship.– Thomas Aquinas",
    "Wishing to be friends is quick work, but friendship is a slow ripening fruit.– Aristotle",
    "I value the friend who for me finds time on his calendar, but I cherish the friend who for me does not consult his calendar.– Robert Brault",
    "Things are never quite as scary when you have a best friend.– Bill Watterson",
    "If you have two friends in your lifetime, you’re lucky. If you have one good friend, you’re more than lucky.– S.E. Hinton",
    "The only way to have a friend is to be one.– Ralph Waldo Emerson",
    "The royal road to a man’s heart is to talk to him about the things he treasures most.— Dale Carnegie",
    "Don’t walk in front of me; I may not follow. Don’t walk behind me; I may not lead. Just walk beside me and be my friend.– Albert Camus",
    "To the world you may be just one person, but to one person you may be the world.– Brandi Snyder",
    "Two things you will never have to chase: True friends & true love.– Mandy Hale",
    "If you have good friends, no matter how much life is sucking, they can make you laugh.– P.C. Cast",
    "Good friends are like stars. You don’t always see them, but you know they’re always there.– Christy Evans",
    "True friends are always together in spirit.– L.M. Montgomery",
    "There is one friend in the life of each of us who seems not a separate person, however dear and beloved, but an expansion, an interpretation, of one’s self, the very meaning of one’s soul.– Edith Wharton",
    "That’s when I realized what a true friend was. Someone who would always love you—the imperfect you, the confused you, the wrong you—because that is what people are supposed to do.– R. J. L. Luis Alvarez",
    "Well, it seems to me that the best relationships – the ones that last – are frequently the ones that are rooted in friendship. You know, one day you look at the person and you see something more than you did the night before. Like a switch has been flicked somewhere. And the person who was just a friend is… suddenly the only person you can ever imagine yourself with.– Gillian Anderson",
    "The essence of true friendship is to make allowance for another’s little lapses.– David Storey",
    "Every friendship goes through ups and downs. Dysfunctional patterns set in; external situations cause internal friction; you grow apart and then bounce back together.– Mariella Frostrup",
    "Friendship is the golden thread that ties the heart of all the world.– John Evelyn",
    "Friendship isn’t a big thing—it’s a million little things.– Paulo Coelho",
    "Getting to know new people and gaining new friends is one of life’s greatest pleasures. So conquer your fears and get out there.– Tony Clark",
    "Experts on romance say for a happy marriage there has to be more than a passionate love. For a lasting union, they insist, there must be a genuine liking for each other. Which, in my book, is a good definition for friendship.– Marilyn Monroe",
    "For it would then be true friendship, such as no hope, no fear, no self-interest can sever. That is a friendship that stays with people until they die—and that people die for.– Lucius Annaeus Seneca",
    "But friendship is precious, not only in the shade, but in the sunshine of life, and thanks to a benevolent arrangement the greater part of life is sunshine.– Thomas Jefferson",
    "One friend with whom you have a lot in common is better than three with whom you struggle to find things to talk about.– Mindy Kaling",
    "Close friends are truly life’s treasures. Sometimes they know us better than we know ourselves.– Vincent Van Gogh",
    "Life is an awful, ugly place to not have a best friend.– Sarah Dessen",
    "A faithful friend is a strong defense; And he that hath found him hath found a treasure.– Louisa May Alcott",
    "One’s life has value so long as one attributes value to the life of others, by means of love, friendship, and compassion.– Simone de Beauvoir",
    "Never leave a friend behind. Friends are all we have to get us through this life–and they are the only things from this world that we could hope to see in the next.– Dean Koontz",
    "If I had a flower for every time I thought of you… I could walk through my garden forever. – Alfred Tennyson",
    "Don’t be afraid of new beginnings. Don’t shy away from new people, new energy, new surroundings. Embrace new chances at happiness.– Billy Chapata",
    "Friendship however is a plant which cannot be forced — true friendship is no gourd spring up in a night and withering in a day.– Charlotte Brontë",
    "A friend can tell you things you don’t want to tell yourself.– Frances Ward Weller",
    "She is a friend of my mind. She gather me, man. The pieces I am, she gather them and give them back to me in all the right order.– Toni Morrison",
    "True friends never apart, maybe in distance but never in heart.– Helen Keller",
    "Each new friendship can make you a new person, because it opens up new doors inside of you.– Kate DiCamillo",
    "Real friendship or love is not manufactured or achieved by an act of will or intention. Friendship is always an act of recognition.– John O’Donohue",
    "‘We’ll be friends forever, won’t we, Pooh?’ asked Piglet. ‘Even longer,’ Pooh answered.– A.A. Milne",
    "One sure way to lose another woman’s friendship is to try to improve her flower arrangements.– Marcelene Cox",
    "Best friends don’t care if your house is clean. They care if you have wine.– Unknown",
    "If you are ever lucky enough to find a weirdo, never let them go.– Matthew Gray Gubler",
    "I love that our effortless friendship fits perfectly with my laziness.– Unknown",
    "A good friend will help you move. But a best friend will help you move a dead body.– Jim Hayes",
    "Friends make you smile — best friends make you giggle ’til you pee your pants.– Terri Guillemets",
    "A true friend is one who overlooks your failures and tolerates your success.– Doug Larson",
    "I think we’ll be friends forever because we’re too lazy to find new friends. – Unknown",
    "One good reason to only maintain a small circle of friends is that three out of four murders are committed by people who know the victim.– George Carlin",
    "Most of us don’t need a psychiatric therapist as much as a friend to be silly with.– Robert Brault",
    "True friendship is when you walk into their house and your WiFi connects automatically.– Unknown",
    "When you’re in jail, a good friend will be trying to bail you out. A best friend will be in the cell next to you saying, Damn, that was fun.– Groucho Marx",
    "True friends are like diamonds – bright, beautiful, valuable, and always in style.– Nicole Richie",
    "Good friends, good books, and a sleepy conscience: this is the ideal life. – Mark Twain",
    "Difficult times help us understand who is your good friend and who is just a friend.– Sukant Ratnakar",
    "Some people go to priests. Others to poetry. I to my friends.– Virginia Woolf",
    "Never let your best friends get lonely… keep disturbing them.– Candlelight Publications",
    "When the world is so complicated, the simple gift of friendship is within all of our hands.– Maria Shriver",
    "Life was meant for good friends and great adventures.– Unknown",
    "Real friendship, like real poetry, is extremely rare — and precious as a pearl.– Tahar Ben Jelloun",
    "In prosperity, our friends know us; in adversity, we know our friends.– John Churton Collins",
    "Two persons cannot long be friends if they cannot forgive each other’s little failings.– Jean de La Bruyère",
    "Friends…they cherish one another’s hopes. They are kind to one another’s dreams.– Henry David Thoreau",
    "Since there is nothing so well worth having as friends, never lose a chance to make them.– Francesco Guicciardini",
    "Remember that life’s most valuable antiques are dear old friends.– H. Jackson Brown, Jr.",
    "Anything is possible when you have the right people there to support you.– Misty Copeland",
    "When a woman becomes her own best friend, life is easier.– Diane von Furstenburg",
    "A faithful friend loves to the end.– Unknown",
    "The greatest gift of life is friendship, and I have received it.– Hubert H. Humphrey",
    "Time doesn’t take away from friendship, nor does separation.– Tennessee Williams",
    "The love that comes from friendship is the underlying facet of a happy life.– Chelsea Handler",
    "The kindest way of helping yourself is to find a friend.– Ann Kaiser Stearns",
    "Dear George: remember, no man is a failure who has friends.– Clarence the Angel (from the classic movie It’s A Wonderful Life)",
    "It’s not that diamonds are a girl’s best friend, but it’s your best friends who are your diamonds.– Gina Barreca",
    "True friends fiercely debate issues and still walk away as friends.– Frank Sonnenberg",
    "Friendship is accepting a person with all their qualities – good and bad.– Mohanlal",
    "Everyone you meet knows something you don’t know but need to know. Learn from them.– C.G. Jung"
];

// Function to display a random quote
function displayQuote() {
    var randomIndex = Math.floor(Math.random() * quotes.length);
    var quote = quotes[randomIndex];
    document.getElementById("quoteText").innerHTML = quote;
}